### Copy this file to config.yml before using the importer.

# Your Todoist API key. You can find this at Settings -> Integrations at the bottom.
api_token: replace_with_your_token

# If you do not actually want to import yet and just want to see the JSON that would be used,
# set this to true.
simulate: false

# Disable the use of Premium features. Useful if you don't have Premium. This will stop the tool
# from using labels and comments, meaning you will lose tag and start date information.
premium: true

# Provide a keyed list of 2Do list to Todoist project mappings. Use names. Todoist project IDs are
# not supported. If you have projects named the same thing, maybe just make a new project
# temporarily and then just move over all the tasks afterward? You can leave out mappings where
# you want to use a project with the same name in Todoist. To map a project to the inbox, enter the key without a value.
list_mapping:
  Professional: Work
  Travel: Vacation
  Inbox:

# Enter list names that you do not want to import into Todoist.
ignore_lists:
  - Templates
  - Testing

# Set to true to not convert tags to labels. Useful if you don't have Premium.
ignore_tags: false


# Testing settings

# If all tasks should be added to the same Todoist project, set this to a project name.
# If the project does not exist, it will be created. 2Do Projects will still cause subprojects
# to be created underneath this one.
test_project_name: Testing
